name: GSC Deploy Workflow

on:
  pull_request:
    branches:
    - __deploy
    types: [closed]


jobs:
  deploy :
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
    steps:
      - name: CheckOut 
        uses: actions/checkout@v2
      - name: Setup - node / npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Build
        run: |-
          npm ci
          npm run build
      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true     
      - name: GSC UPload
        run: |-
          gsutil rm -r "gs://$GCS_BUCKET/**"
          gsutil -m rsync -R build gs://$GCS_BUCKET
